set -g status-bg "#222222"
set -g status-fg "#c2c2b0"
set -g status-left "#[fg=#78997a,bold] #S "
set -g status-right "#[fg=#bca063] %H:%M "
set -g window-status-current-style "fg=#222222,bg=#78997a,bold"
