# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d07d1557-3b35-4ac5-a0d2-6d988b149b93";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-d07d1557-3b35-4ac5-a0d2-6d988b149b93".device = "/dev/disk/by-uuid/d07d1557-3b35-4ac5-a0d2-6d988b149b93";
  boot.initrd.luks.devices."luks-9e8cd706-9861-4505-9dd1-56eeb4e00bce".device = "/dev/disk/by-uuid/9e8cd706-9861-4505-9dd1-56eeb4e00bce";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-d07d1557-3b35-4ac5-a0d2-6d988b149b93";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d07d1557-3b35-4ac5-a0d2-6d988b149b93";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9D48-D6F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9e8cd706-9861-4505-9dd1-56eeb4e00bce"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
