set -g status-bg "#1f1f28"
set -g status-fg "#dcd7ba"
set -g status-left "#[fg=#957fb8,bold] #S "
set -g status-right "#[fg=#7aa89f] %H:%M "
set -g window-status-current-style "fg=#1f1f28,bg=#957fb8,bold"
