#!/usr/bin/env bash

ROFI_THEME="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/hub.rasi"
STATE_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/fonts/settings.json"

if [ -f "$ROFI_THEME" ]; then
    ROFI_CMD="rofi -dmenu -theme $ROFI_THEME"
else
    ROFI_CMD="rofi -dmenu"
fi

mkdir -p "$(dirname "$STATE_FILE")"

# Load saved state or defaults
CURRENT_FAMILY="JetBrainsMono Nerd Font"
CURRENT_SIZE=12

if [ -f "$STATE_FILE" ] && command -v jq >/dev/null 2>&1; then
    saved_family=$(jq -r '.family // empty' "$STATE_FILE" 2>/dev/null)
    saved_size=$(jq -r '.size // empty' "$STATE_FILE" 2>/dev/null)
    [ -n "$saved_family" ] && CURRENT_FAMILY="$saved_family"
    [ -n "$saved_size" ] && CURRENT_SIZE="$saved_size"
fi

apply_font() {
    local family="$1"
    local size="$2"

    mkdir -p "$(dirname "$STATE_FILE")"
    if command -v jq >/dev/null 2>&1; then
        jq -n --arg f "$family" --argjson s "$size" '{family: $f, size: $s}' > "$STATE_FILE"
    else
        echo "{\"family\":\"$family\",\"size\":$size}" > "$STATE_FILE"
    fi

    # 1. Update Kitty font config and reload live terminals
    mkdir -p "$HOME/.config/kitty"
    cat > "$HOME/.config/kitty/font.conf" <<EOF
# Automatically generated by font-switcher.sh
font_family      $family
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        ${size}.0
EOF
    pkill -USR1 -f kitty 2>/dev/null || true

    # 2. Update Rofi dynamic font file
    mkdir -p "$HOME/.config/rofi"
    cat > "$HOME/.config/rofi/font.rasi" <<EOF
/* Automatically generated by font-switcher.sh */
* {
    font: "$family $size";
}
EOF

    # 3. Update Quickshell FontConfig singleton & reload bar
    mkdir -p "$HOME/.config/quickshell"
    local small_size=$(( size > 10 ? size - 2 : 9 ))
    cat > "$HOME/.config/quickshell/FontConfig.qml" <<EOF
pragma Singleton
import QtQuick

QtObject {
    readonly property string family: "$family"
    readonly property int sizeNormal: $size
    readonly property int sizeSmall: $small_size
}
EOF

    if pidof quickshell >/dev/null 2>&1; then
        pkill quickshell 2>/dev/null || true
        while pidof quickshell >/dev/null 2>&1; do sleep 0.05; done
        quickshell >/dev/null 2>&1 &
    fi

    # 4. Update GNOME / GTK settings for GUI apps
    local gtk_size=$(( size > 11 ? size - 1 : 10 ))
    gsettings set org.gnome.desktop.interface font-name "$family $gtk_size" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface monospace-font-name "$family $size" 2>/dev/null || true

    notify-send -a "Font Switcher" -i preferences-desktop-font "Font Updated" "$family — ${size}pt" 2>/dev/null || true
}

pick_family() {
    local options="󰌌  Back\nJetBrainsMono Nerd Font\nFiraCode Nerd Font\nHack Nerd Font\nIosevka Nerd Font"
    local chosen
    chosen=$(echo -e "$options" | $ROFI_CMD -p "Family")

    case "$chosen" in
        *"Back"*|"")
            return 0
            ;;
        *)
            CURRENT_FAMILY="$chosen"
            apply_font "$CURRENT_FAMILY" "$CURRENT_SIZE"
            ;;
    esac
}

pick_size() {
    local options="󰌌  Back\n10 pt (Compact)\n11 pt (Small)\n12 pt (Default)\n13 pt (Medium)\n14 pt (Large)\n16 pt (Extra Large)"
    local chosen
    chosen=$(echo -e "$options" | $ROFI_CMD -p "Size")

    case "$chosen" in
        *"Back"*|"")
            return 0
            ;;
        "10"*)
            CURRENT_SIZE=10
            ;;
        "11"*)
            CURRENT_SIZE=11
            ;;
        "12"*)
            CURRENT_SIZE=12
            ;;
        "13"*)
            CURRENT_SIZE=13
            ;;
        "14"*)
            CURRENT_SIZE=14
            ;;
        "16"*)
            CURRENT_SIZE=16
            ;;
        *)
            return 0
            ;;
    esac
    apply_font "$CURRENT_FAMILY" "$CURRENT_SIZE"
}

# Main Font Menu loop
while true; do
    options="󰌌  Back\n  Font Family: $CURRENT_FAMILY\n󰑐  Font Size: ${CURRENT_SIZE} pt\n󰹍  Increase Size (+1 pt)\n󰹎  Decrease Size (-1 pt)\n↺  Reset to Default (12 pt)"
    chosen=$(echo -e "$options" | $ROFI_CMD -p "Font Settings")

    case "$chosen" in
        *"Back"*|"")
            exit 0
            ;;
        *"Font Family:"*)
            pick_family
            ;;
        *"Font Size:"*)
            pick_size
            ;;
        *"+1 pt"*)
            if [ "$CURRENT_SIZE" -lt 20 ]; then
                CURRENT_SIZE=$(( CURRENT_SIZE + 1 ))
                apply_font "$CURRENT_FAMILY" "$CURRENT_SIZE"
            fi
            ;;
        *"-1 pt"*)
            if [ "$CURRENT_SIZE" -gt 9 ]; then
                CURRENT_SIZE=$(( CURRENT_SIZE - 1 ))
                apply_font "$CURRENT_FAMILY" "$CURRENT_SIZE"
            fi
            ;;
        *"Reset"*)
            CURRENT_FAMILY="JetBrainsMono Nerd Font"
            CURRENT_SIZE=12
            apply_font "$CURRENT_FAMILY" "$CURRENT_SIZE"
            ;;
        *)
            exit 0
            ;;
    esac
done
